# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.ImageField(upload_to=b'')),
                ('article_title', models.CharField(max_length=254)),
                ('article_content', models.CharField(max_length=254)),
                ('article_genre', models.IntegerField(choices=[('', '---------'), ('1', 'politics'), ('2', 'sports'), ('3', 'science'), ('4', 'entertainment'), ('5', 'world'), ('6', 'nation'), ('7', 'environment'), ('8', 'businessandcommerce')])),
                ('article_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Article_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=254)),
                ('question_type', models.IntegerField(choices=[('', '---------'), ('1', 'multiple choice questions'), ('2', 'more than one correct choice'), ('3', 'true or false'), ('4', 'fill in the blanks'), ('5', 'edit the sentence'), ('6', 'match the following')])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishapp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_type', models.IntegerField(choices=[('', '---------'), ('1', 'ssc preparation'), ('2', 'bank preparation'), ('3', 'others')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question_choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice1_description', models.CharField(blank=True, max_length=254)),
                ('choice2_description', models.CharField(blank=True, max_length=254)),
                ('choice3_description', models.CharField(blank=True, max_length=254)),
                ('choice4_description', models.CharField(blank=True, max_length=254)),
                ('fill_blank_description', models.CharField(blank=True, max_length=254)),
                ('right_choice', models.IntegerField(choices=[('', '---------'), ('1', 'choice1'), ('2', 'choice2'), ('3', 'choice3'), ('4', 'choice4'), ('5', 'fill in the blank'), ('6', 'True'), ('7', 'False')])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishapp.Article_Questions')),
            ],
        ),
        migrations.CreateModel(
            name='User_Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=254)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='englishapp.Article_Questions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
