# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='staticfiles/images/article_images'),
        ),
    ]
