# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('englishapp', '0002_auto_20161015_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_genre',
            field=models.IntegerField(choices=[('', '---------'), (1, 'politics'), (2, 'sports'), (3, 'science'), (4, 'entertainment'), (5, 'world'), (6, 'nation'), (7, 'environment'), (8, 'businessandcommerce')]),
        ),
    ]
