# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 11:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('englishapp', '0003_auto_20161015_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_publication_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 22, 11, 8, 32, 47000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_publication_source',
            field=models.CharField(default='ahha', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_publication_source_url',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='article_summary',
            field=models.CharField(default='jdjd', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='englishgyani/staticfiles/images/article_images'),
        ),
    ]
